In [33]:
import numpy as np
import matplotlib.pyplot as pyp

In [34]:
dataset = np.load('pts.npy')

In [35]:
M = dataset.mean(axis=0, keepdims=True)

In [36]:
#calculate the mean of the dataset
M

array([[-0.1025569 , -6.42222282]])

In [37]:
dataset[:10]

array([[ 6.34838306e+00, -6.43671259e+01],
       [ 9.86381827e+00, -8.27317880e+01],
       [-9.48214968e+00,  6.16270204e+01],
       [ 2.83024455e+00, -2.00380669e+01],
       [-1.56129159e-02, -7.20337168e+00],
       [-5.64956740e+00,  3.45951791e+01],
       [-9.16896106e+00,  6.19980038e+01],
       [-3.78415655e+00,  3.70528588e+01],
       [-7.17647279e+00,  4.84074079e+01],
       [-4.24670288e+00,  1.03057126e+01]])

In [38]:
#construct new dataset from original dataset minus mean
datasetMinusMean = dataset - M
datasetMinusMean[:10]

array([[  6.45093996, -57.94490307],
       [  9.96637517, -76.3095652 ],
       [ -9.37959278,  68.04924325],
       [  2.93280145, -13.6158441 ],
       [  0.08694398,  -0.78114886],
       [ -5.54701051,  41.01740195],
       [ -9.06640416,  68.4202266 ],
       [ -3.68159965,  43.47508164],
       [ -7.07391589,  54.82963069],
       [ -4.14414598,  16.72793547]])

In [39]:
#calculate the covariance matrix using numpy
covMatrix = np.cov(datasetMinusMean)
covMatrix

array([[ 2073.41229969,  2777.9059565 , -2493.04758529, ...,
        -1494.21115405,  -861.18384537, -1161.56193021],
       [ 2777.9059565 ,  3721.76894307, -3340.12281978, ...,
        -2001.90674365, -1153.79258339, -1556.23163095],
       [-2493.04758529, -3340.12281978,  2997.61232411, ...,
         1796.62265439,  1035.47775158,  1396.64897604],
       ...,
       [-1494.21115405, -2001.90674365,  1796.62265439, ...,
         1076.80801027,   620.61487126,   837.08329139],
       [ -861.18384537, -1153.79258339,  1035.47775158, ...,
          620.61487126,   357.6894068 ,   482.45029213],
       [-1161.56193021, -1556.23163095,  1396.64897604, ...,
          837.08329139,   482.45029213,   650.72736277]])

In [40]:
#run SVD
U, s, V = np.linalg.svd(covMatrix)

In [41]:
U.shape

(100, 100)

In [42]:
U

array([[-0.12565529, -0.24594266, -0.36897931, ..., -0.17734926,
        -0.16008403, -0.01650389],
       [-0.16834982,  0.07348402, -0.15832282, ..., -0.07625108,
         0.37245415,  0.2510962 ],
       [ 0.15108651, -0.1239573 ,  0.19530492, ..., -0.03044031,
         0.22685958,  0.17682143],
       ...,
       [ 0.09055389, -0.02402072, -0.12739881, ..., -0.0267812 ,
         0.11573147, -0.07175328],
       [ 0.05219044,  0.05288385,  0.02045117, ...,  0.05789257,
         0.04544961, -0.06322065],
       [ 0.0703943 , -0.02868207,  0.11212719, ...,  0.01409971,
         0.00938438,  0.08254019]])

In [43]:
s.shape

(100,)

In [44]:
s

array([1.31317947e+05, 7.65137674e-11, 6.94036981e-11, 6.14576396e-11,
       5.51582107e-11, 5.03695737e-11, 4.54952884e-11, 4.41050669e-11,
       4.01895927e-11, 3.22449897e-11, 2.38938531e-11, 1.95030617e-11,
       1.78238730e-11, 1.30172989e-11, 1.30172989e-11, 1.30172989e-11,
       1.30172989e-11, 1.30172989e-11, 1.30172989e-11, 1.30172989e-11,
       1.30172989e-11, 1.30172989e-11, 1.30172989e-11, 1.30172989e-11,
       1.30172989e-11, 1.30172989e-11, 1.30172989e-11, 1.30172989e-11,
       1.30172989e-11, 1.30172989e-11, 1.30172989e-11, 1.30172989e-11,
       1.30172989e-11, 1.30172989e-11, 1.30172989e-11, 1.30172989e-11,
       1.30172989e-11, 1.30172989e-11, 1.30172989e-11, 1.30172989e-11,
       1.30172989e-11, 1.30172989e-11, 1.30172989e-11, 1.30172989e-11,
       1.30172989e-11, 1.30172989e-11, 1.30172989e-11, 1.30172989e-11,
       1.30172989e-11, 1.30172989e-11, 1.30172989e-11, 1.30172989e-11,
       1.30172989e-11, 1.30172989e-11, 1.30172989e-11, 1.30172989e-11,
      

In [45]:
V.shape

(100, 100)

In [46]:
V

array([[-1.25655294e-01, -1.68349822e-01,  1.51086510e-01, ...,
         9.05538867e-02,  5.21904446e-02,  7.03942995e-02],
       [-2.04094107e-02,  6.27698178e-01,  6.89716953e-01, ...,
        -1.36814715e-02,  1.43543353e-02, -2.94544308e-02],
       [ 4.07317379e-03, -8.48624346e-02, -9.92906512e-02, ...,
        -6.25210073e-03,  1.08986338e-02,  1.05917705e-03],
       ...,
       [ 0.00000000e+00,  2.53667217e-02,  7.33792387e-03, ...,
         3.46067685e-03,  2.31304079e-02, -4.71245028e-03],
       [ 4.81808419e-01,  2.36724016e-02,  4.93366279e-02, ...,
        -7.66698064e-02,  9.85305359e-03, -1.66048427e-02],
       [ 8.27518184e-01,  1.09293101e-01, -1.52845725e-01, ...,
         6.45782122e-02,  4.67515695e-04,  2.70609898e-02]])

In [47]:
#reconstruct the original covariance matrix using the SVD decomposition
S = np.diag(s)
reconstructed = np.dot(U, np.dot(S, V))

In [48]:
reconstructed

array([[ 2073.41229969,  2777.9059565 , -2493.04758529, ...,
        -1494.21115405,  -861.18384537, -1161.56193021],
       [ 2777.9059565 ,  3721.76894307, -3340.12281978, ...,
        -2001.90674365, -1153.79258339, -1556.23163095],
       [-2493.04758529, -3340.12281978,  2997.61232411, ...,
         1796.62265439,  1035.47775158,  1396.64897604],
       ...,
       [-1494.21115405, -2001.90674365,  1796.62265439, ...,
         1076.80801027,   620.61487126,   837.08329139],
       [ -861.18384537, -1153.79258339,  1035.47775158, ...,
          620.61487126,   357.6894068 ,   482.45029213],
       [-1161.56193021, -1556.23163095,  1396.64897604, ...,
          837.08329139,   482.45029213,   650.72736277]])

In [49]:
np.allclose(covMatrix, np.dot(U, np.dot(S, V)))

True