In [86]:
import numpy as np
import matplotlib.pyplot as plt

In [87]:
X = np.ones(3)
X

array([1., 1., 1.])

In [88]:
W1 = np.array([ [1,2,3], [4,5,6], [7,8,9]])
W1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [89]:
W2 = np.array([ [1,1,0], [0,1,1], [1,0,1]])
W2

array([[1, 1, 0],
       [0, 1, 1],
       [1, 0, 1]])

In [90]:
H1 = np.dot(W1,X) 
H1

array([ 6., 15., 24.])

In [91]:
W2 = np.array( [[1,1,0], [0,1,1], [1,0,1]])

In [92]:
H2 = np.dot(W2, H1)
H2

array([21., 39., 30.])

In [93]:
cols = 3
rows = 3

tensor_data = []

for j in range(3):
    data = []
    for r in range(rows):
        if r == j:
            row = [1] * cols
        else:
            row = [0] * cols
        data.append(row)
    tensor_data.append(data)

t = np.array(tensor_data)
t

array([[[1, 1, 1],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [1, 1, 1],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [1, 1, 1]]])

In [94]:
dH2_dW2 = t * H1
dH2_dW2

array([[[ 6., 15., 24.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.]],

       [[ 0.,  0.,  0.],
        [ 6., 15., 24.],
        [ 0.,  0.,  0.]],

       [[ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 6., 15., 24.]]])

In [95]:
## dH2_dW1
dH1_dW1 = t * W2
dH1_dW1

array([[[1, 1, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 1, 1],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [1, 0, 1]]])

In [160]:
dH2_dW1 = np.tensordot(W2,t,1)
dH2_dW1

array([[[1, 1, 1],
        [1, 1, 1],
        [0, 0, 0]],

       [[0, 0, 0],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [0, 0, 0],
        [1, 1, 1]]])