In [30]:
import numpy as np
import matplotlib.pyplot as pyp

In [31]:
#page rank matrix
L = np.matrix([[0, 1/2, 0, 0], [1/3, 0, 0, 1/2], [1/3, 0, 0, 1/2], [1/3, 1/2, 1, 0]])


In [32]:
L

matrix([[0.        , 0.5       , 0.        , 0.        ],
        [0.33333333, 0.        , 0.        , 0.5       ],
        [0.33333333, 0.        , 0.        , 0.5       ],
        [0.33333333, 0.5       , 1.        , 0.        ]])

In [33]:
W, V = np.linalg.eig(L)

In [34]:
#eigenvalues
W

array([ 1.00000000e+00, -9.17517095e-02, -9.08248290e-01,  5.88174157e-17])

In [35]:
#eigenvectors
V

matrix([[-2.22988244e-01, -8.25340062e-01,  2.62323812e-01,
         -8.01783726e-01],
        [-4.45976488e-01,  1.51452723e-01, -4.76510307e-01,
         -1.04906215e-16],
        [-4.45976488e-01,  1.51452723e-01, -4.76510307e-01,
          2.67261242e-01],
        [-7.43294146e-01,  5.22434615e-01,  6.90696802e-01,
          5.34522484e-01]])

In [36]:
L.shape

(4, 4)

In [37]:
r = np.random.random((4,1))
r

array([[0.39677593],
       [0.16802721],
       [0.64939343],
       [0.30107958]])

In [38]:
r = np.array([[0.25], [0.25], [0.25], [0.25]])
r

array([[0.25],
       [0.25],
       [0.25],
       [0.25]])

In [39]:
print("several iteration of page-rank algorithm fiding ranks of some webpages")
for i in range(100):
    r = L.dot(r)
    r = r / np.linalg.norm(r)
    print(r.T)

several iteration of page-rank algorithm fiding ranks of some webpages
[[0.2236068  0.372678   0.372678   0.81989159]]
[[0.19581511 0.50911929 0.50911929 0.66577138]]
[[0.24620506 0.38508996 0.38508996 0.80174467]]
[[0.19872764 0.49844803 0.49844803 0.68088652]]
[[0.24259975 0.39587627 0.39587627 0.79228108]]
[[0.20313953 0.48954186 0.48954186 0.69241018]]
[[0.23934942 0.40475026 0.40475026 0.78426164]]
[[0.20674167 0.48209619 0.48209619 0.70172958]]
[[0.2366074  0.41204534 0.41204534 0.77746654]]
[[0.20967442 0.47589066 0.47589066 0.70929035]]
[[0.23430561 0.41804274 0.41804274 0.77173921]]
[[0.21206645 0.47073073 0.47073073 0.71543902]]
[[0.23237998 0.42297438 0.42297438 0.76693213]]
[[0.21402069 0.46644771 0.46644771 0.72045   ]]
[[0.2307734  0.42703083 0.42703083 0.76291086]]
[[0.21561964 0.4628973  0.4628973  0.72454148]]
[[0.22943589 0.43036849 0.43036849 0.75955586]]
[[0.21692956 0.45995716 0.45995716 0.72788762]]
[[0.22832431 0.43311563 0.43311563 0.75676266]]
[[0.2180039  0.45

In [40]:
#r converges to the largest eigenvector 
w, v = np.linalg.eig(L)
#print the largest eigenvector (scaled by some scalar)
print("the largest eigenvector computed by numpy (that's what page-rank finds but scaled):")
print(v[:,0])
print("ratio of numpy eigv by page rank eigv (if all numbers are close the vectors are likely from the same eigenspace):")
print(v[:,0] / r.T)

the largest eigenvector computed by numpy (that's what page-rank finds but scaled):
[[-0.22298824]
 [-0.44597649]
 [-0.44597649]
 [-0.74329415]]
ratio of numpy eigv by page rank eigv (if all numbers are close the vectors are likely from the same eigenspace):
[[-1.00001    -0.4999941  -0.4999941  -0.30000228]
 [-2.00002    -0.9999882  -0.9999882  -0.60000456]
 [-2.00002    -0.9999882  -0.9999882  -0.60000456]
 [-3.33336667 -1.66664699 -1.66664699 -1.0000076 ]]


In [41]:
h = 1./500.
h

0.002

In [42]:
xs = (-5) + np.array(range(0, (int) (1/h))) * 10 * h
xs

array([-5.  , -4.98, -4.96, -4.94, -4.92, -4.9 , -4.88, -4.86, -4.84,
       -4.82, -4.8 , -4.78, -4.76, -4.74, -4.72, -4.7 , -4.68, -4.66,
       -4.64, -4.62, -4.6 , -4.58, -4.56, -4.54, -4.52, -4.5 , -4.48,
       -4.46, -4.44, -4.42, -4.4 , -4.38, -4.36, -4.34, -4.32, -4.3 ,
       -4.28, -4.26, -4.24, -4.22, -4.2 , -4.18, -4.16, -4.14, -4.12,
       -4.1 , -4.08, -4.06, -4.04, -4.02, -4.  , -3.98, -3.96, -3.94,
       -3.92, -3.9 , -3.88, -3.86, -3.84, -3.82, -3.8 , -3.78, -3.76,
       -3.74, -3.72, -3.7 , -3.68, -3.66, -3.64, -3.62, -3.6 , -3.58,
       -3.56, -3.54, -3.52, -3.5 , -3.48, -3.46, -3.44, -3.42, -3.4 ,
       -3.38, -3.36, -3.34, -3.32, -3.3 , -3.28, -3.26, -3.24, -3.22,
       -3.2 , -3.18, -3.16, -3.14, -3.12, -3.1 , -3.08, -3.06, -3.04,
       -3.02, -3.  , -2.98, -2.96, -2.94, -2.92, -2.9 , -2.88, -2.86,
       -2.84, -2.82, -2.8 , -2.78, -2.76, -2.74, -2.72, -2.7 , -2.68,
       -2.66, -2.64, -2.62, -2.6 , -2.58, -2.56, -2.54, -2.52, -2.5 ,
       -2.48, -2.46,

In [43]:
## - x^2 / 4 - y^2 / 4 + 2

## -x**2 / 4 - y**2 / 4 + 2

def funcc(x,y):
    return -(x**2) / 4 - y**2 / 4 + 2

## f/x(x,y) = (f(x+h,y) - f(x,y))   / h
## f/y(x,y) = (f(x,y+h) - f(x,y))   / h


##ys = [ ( ()  - () )/h  for x in xs ]

In [44]:
## 1 / (1 + e ^ (-x-y))

def funcccc(x):
    return  1/(1 + np.exp(-(x)-(y)))


In [45]:
#x = np.arange(-5, 5, 10./500.)

In [46]:
#import itertools
#bloop = [zip(x,xs) for x in itertools.permutations(xs,len(xs))]
#bloop[:50]

In [47]:
res = []
for x in xs:
    for y in xs:
        res.append((x,y))

In [48]:
res[27030]

(-3.92, -4.4)

In [61]:
x = np.arange(-5, 5, 1)
y = np.arange(-5, 5, 1)


x = x.reshape( (10,1) )
y = y.reshape( (1, 10) )

In [62]:
x

array([[-5],
       [-4],
       [-3],
       [-2],
       [-1],
       [ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4]])

In [63]:
y

array([[-5, -4, -3, -2, -1,  0,  1,  2,  3,  4]])

In [69]:
-x-y

array([[10,  9,  8,  7,  6,  5,  4,  3,  2,  1],
       [ 9,  8,  7,  6,  5,  4,  3,  2,  1,  0],
       [ 8,  7,  6,  5,  4,  3,  2,  1,  0, -1],
       [ 7,  6,  5,  4,  3,  2,  1,  0, -1, -2],
       [ 6,  5,  4,  3,  2,  1,  0, -1, -2, -3],
       [ 5,  4,  3,  2,  1,  0, -1, -2, -3, -4],
       [ 4,  3,  2,  1,  0, -1, -2, -3, -4, -5],
       [ 3,  2,  1,  0, -1, -2, -3, -4, -5, -6],
       [ 2,  1,  0, -1, -2, -3, -4, -5, -6, -7],
       [ 1,  0, -1, -2, -3, -4, -5, -6, -7, -8]])

In [64]:
x.dot(y)

array([[ 25,  20,  15,  10,   5,   0,  -5, -10, -15, -20],
       [ 20,  16,  12,   8,   4,   0,  -4,  -8, -12, -16],
       [ 15,  12,   9,   6,   3,   0,  -3,  -6,  -9, -12],
       [ 10,   8,   6,   4,   2,   0,  -2,  -4,  -6,  -8],
       [  5,   4,   3,   2,   1,   0,  -1,  -2,  -3,  -4],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [ -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4],
       [-10,  -8,  -6,  -4,  -2,   0,   2,   4,   6,   8],
       [-15, -12,  -9,  -6,  -3,   0,   3,   6,   9,  12],
       [-20, -16, -12,  -8,  -4,   0,   4,   8,  12,  16]])

In [68]:
(x ** 2) / 4 - (y ** 2) / 4 + 2

array([[ 2.  ,  4.25,  6.  ,  7.25,  8.  ,  8.25,  8.  ,  7.25,  6.  ,
         4.25],
       [-0.25,  2.  ,  3.75,  5.  ,  5.75,  6.  ,  5.75,  5.  ,  3.75,
         2.  ],
       [-2.  ,  0.25,  2.  ,  3.25,  4.  ,  4.25,  4.  ,  3.25,  2.  ,
         0.25],
       [-3.25, -1.  ,  0.75,  2.  ,  2.75,  3.  ,  2.75,  2.  ,  0.75,
        -1.  ],
       [-4.  , -1.75,  0.  ,  1.25,  2.  ,  2.25,  2.  ,  1.25,  0.  ,
        -1.75],
       [-4.25, -2.  , -0.25,  1.  ,  1.75,  2.  ,  1.75,  1.  , -0.25,
        -2.  ],
       [-4.  , -1.75,  0.  ,  1.25,  2.  ,  2.25,  2.  ,  1.25,  0.  ,
        -1.75],
       [-3.25, -1.  ,  0.75,  2.  ,  2.75,  3.  ,  2.75,  2.  ,  0.75,
        -1.  ],
       [-2.  ,  0.25,  2.  ,  3.25,  4.  ,  4.25,  4.  ,  3.25,  2.  ,
         0.25],
       [-0.25,  2.  ,  3.75,  5.  ,  5.75,  6.  ,  5.75,  5.  ,  3.75,
         2.  ]])

In [77]:
tt = 1/(1 + np.exp(np.matrix(-(x)-(y))))
tt

matrix([[4.53978687e-05, 1.23394576e-04, 3.35350130e-04, 9.11051194e-04,
         2.47262316e-03, 6.69285092e-03, 1.79862100e-02, 4.74258732e-02,
         1.19202922e-01, 2.68941421e-01],
        [1.23394576e-04, 3.35350130e-04, 9.11051194e-04, 2.47262316e-03,
         6.69285092e-03, 1.79862100e-02, 4.74258732e-02, 1.19202922e-01,
         2.68941421e-01, 5.00000000e-01],
        [3.35350130e-04, 9.11051194e-04, 2.47262316e-03, 6.69285092e-03,
         1.79862100e-02, 4.74258732e-02, 1.19202922e-01, 2.68941421e-01,
         5.00000000e-01, 7.31058579e-01],
        [9.11051194e-04, 2.47262316e-03, 6.69285092e-03, 1.79862100e-02,
         4.74258732e-02, 1.19202922e-01, 2.68941421e-01, 5.00000000e-01,
         7.31058579e-01, 8.80797078e-01],
        [2.47262316e-03, 6.69285092e-03, 1.79862100e-02, 4.74258732e-02,
         1.19202922e-01, 2.68941421e-01, 5.00000000e-01, 7.31058579e-01,
         8.80797078e-01, 9.52574127e-01],
        [6.69285092e-03, 1.79862100e-02, 4.74258732e-02, 1.1

In [78]:
tt.shape

(10, 10)

In [53]:
x

array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4])

In [54]:
xx, yy = np.meshgrid(x, y, sparse=True)

In [55]:
xx

array([[-5, -4, -3, -2, -1,  0,  1,  2,  3,  4]])

In [56]:
yy

array([[-5],
       [-4],
       [-3],
       [-2],
       [-1],
       [ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4]])

In [57]:
testM = np.matrix([[]])

In [58]:
testM

matrix([], shape=(1, 0), dtype=float64)

In [59]:
testM[0]

matrix([], shape=(1, 0), dtype=float64)

In [60]:
gradx = (np.sin( (xs +h).dot(ys) ) - np.sin( xs.dot(ys) ) ) / h 
grady = (np.sin( xs.dot( ys +h) ) - np.sin( xs.dot(ys) ) ) / h

NameError: name 'ys' is not defined

In [ ]:
### PART C
import numpy as np
import matplotlib.pyplot as pyp
import math

In [ ]:
h = 0.001
xs = np.array(range(0,(int)(1/h)))  * h

In [ ]:
##-(x**2) / 4 - (1/4) + 2

def equaA(x):
    return -(x**2) / 4 - (1/4) + 2

ysA = [ (equaA(x+h) - equaA(x) )/h  for x in xs ]

In [ ]:
## 1/(1 + np.exp(-x-1))

def equaB(x):
    return  1/(1 + np.exp(-(x)-1))

ysB = [ (equaB(x+h) - equaB(x) )/h  for x in xs ]

In [ ]:
ysA

In [ ]:
ysB

In [ ]:
pyp.subplot(2,1,1)
pyp.plot(xs, ysA)
pyp.title("A")

pyp.show()

In [ ]:
pyp.subplot(2,1,1)
pyp.plot(xs, ysB)
pyp.title("B")

pyp.show()